version: '3.7'

# DATABASE_URL: postgres://username:pgpassword@db:5432/mydatabasee

services:
  # postgres running on its own ec2 instead
  # mongo:
  #   image: mongo:latest
  #   container_name: mongo
  #   restart: always

  cast-and-crew:
    build:
      context: .
    image: castandcrew:latest
    container_name: castandcrew
    ports:
    - "3000:3000"